### PR TITLE
DBT 379 add new organizational units to mir institutes

### PR DESCRIPTION
**Pull request by Antoniafriedrich**
[Link to jira](https://mycore.atlassian.net/browse/DBT-379).

### CODE REVIEW

**Comment by adlerre** [comment]
Please commit only changes!

**Comment by Antoniafriedrich** [comment]
My second commit is only the changes requested in the ticket. The first one is considering the changes on the institutes done in the dbt directly, so uploading the new file causes no incompatibilities or errors. 

Would you like me to revert the first commit?

**Comment by adlerre** [comment]
> Would you like me to revert the first commit?

Yes and the last one. It's easier to track changes.

**Comment by Antoniafriedrich** [comment]
For tracking changes it is possible to view the commits seperately. If reverting them is wanted, how should I make sure the changes are up to date with the dbt institutes? With a seperate pull request? What do you suggest?

**Review by adlerre — APPROVED** [review]

**Pull request merged**
